package model;

public enum TutorialStep {
	CLICK_TOWER, PLACE_TOWER, SPAWN_ITEM, CLICK_ITEM, PLACE_ITEM, SPAWN_WRONG_ITEM, CLICK_WRONG_ITEM, PLACE_WRONG_ITEM, CLICK_GABBION, PLACE_GABBION, DONE
}
